name: Release

on:
  release:
    types: [published]

  workflow_dispatch:    
    inputs:
      tag_name:
        description: "Release Tag Name"
        required: true

permissions:
  contents: write

env:
  tag_name: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
  nim_ver: 2.2.6
  mount_ver: 1.0.0

jobs:
  bump-version:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: main

        - name: Set up Git user
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: Update files
          run: |
            VERSION="${{ env.tag_name }}"

            sed -i "s/^version *= *\".*\"/version = \"$VERSION\"/" wewbo.nimble
            echo "const ver* = \"$VERSION\"" > src/version.nim

        - name: Commit and push changes
          run: |
            git add wewbo.nimble src/version.nim
            
            if ! git diff-index --quiet HEAD; then
              git commit -m "chore: bump version to ${{ env.tag_name }}"
              git push origin main
            else
              echo "No changes detected, skipping commit."
            fi

  build-linux-release:
    runs-on: ubuntu-latest
    if: github.event.release != null
    needs: bump-version
    steps:
      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install --yes musl-tools      

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.nim_ver }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Linux binary
        run: |
          nimble install illwill q htmlparser malebolgia zippy -y
          nim musl -d:pcre -d:openssl -d:release --mm:arc src/wewbo.nim

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/wewbo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-release:
    runs-on: windows-latest
    if: github.event.release != null
    needs: bump-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Download and extract wewbo DLL
        run: |
          Invoke-WebRequest -Uri "https://github.com/upi-0/wewbo/releases/download/${{ env.mount_ver }}/wewbo-dll.zip" -OutFile "wewbo-dll.zip"
          Expand-archive -Path "wewbo-dll.zip" -DestinationPath "build"

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ env.nim_ver }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Windows Library
        run: |
          nimble install illwill q htmlparser malebolgia zippy -y
          nim c -d:release --mm:arc --multimethods:on "src/wewbo"

      - name: Compress Builded Directory
        run: Compress-archive -Path "build/*" -DestinationPath "wewbo-win.${{ env.tag_name }}.zip"

      - name: Create scoop manifest json
        run: | 
          $version = "${{ env.tag_name }}"
          $bin = "wewbo.exe"
          $hash = "sha256:" + (Get-Filehash -Path "wewbo-win.${{ env.tag_name }}.zip").Hash
          $url = "${{ github.server_url }}/${{ github.repository }}/releases/download/$version/wewbo-win.$version.zip"
          $homepage = "https://github.com/upi-0/wewbo"
          
          $manifest = @{
            version = $version
            hash = $hash
            url = $url
            bin = $bin
            homepage = $homepage
          }

          $manifest | ConvertTo-Json > wewbo.json

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wewbo-win.${{ env.tag_name }}.zip
            wewbo.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
